required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.4.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.9"

[[override]]
  name = "knative.dev/pkg"
  branch = "release-0.9"

[[override]]
  name = "github.com/knative/eventing"
  version = "0.9.0"

[[override]]
  name = "knative.dev/serving"
  version = "0.9.0"
