[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.9"

[[override]]
  name = "github.com/knative/pkg"
  branch = "release-0.8"

[[override]]
  name = "github.com/knative/eventing"
  version = "0.8.0"

[[override]]
  name = "github.com/knative/serving"
  version = "0.8.0"
