[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.6"

[[override]]
  name = "github.com/knative/pkg"
  branch = "release-0.7"

[[override]]
  name = "github.com/knative/eventing"
  version = "0.7.0"

[[override]]
  name = "github.com/knative/serving"
  version = "0.7.0"

[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  version = "0.7.0"
