apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: graph
spec:
  template:
    spec:
      serviceAccountName: n3wscott-graph
      containers:
        - image: github.com/n3wscott/graph/cmd/graph
          env:
            - name: NAMESPACE
              value: default
