apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: graph
spec:
  template:
    spec:
      containers:
        - image: github.com/n3wscott/graph/cmd/graph
          serviceAccountName: n3wscott-graph
          env:
            - name: NAMESPACE
              value: default
